module.exports : {
  LEVELFX_LOGARITHM_BASE : 10,
  Foursquare: {
    ONE_KILOMETER_PASSED : 1;
    BASE_CHECKIN : 10;
    ONE_LIKE_TO_CHECKIN : BASE_CHECKIN * 2;
    CHECKIN_WITH_PHOTO : BASE_CHECKIN * 2;
    ONE_COMMENT_TO_CHECKIN : BASE_CHECKIN * 3;
    NEW_PLACE_CHECKIN : BASE_CHECKIN * 5;
    MAYORSHIP_CHECKIN : BASE_CHECKIN * 5;
    CHECKIN_WITH_NEW_FOURSQUARE_CLIENT : BASE_CHECKIN * 5;
    CHECKIN_AT_PLACE_WITH_MORE_THAN_100_CHECKINS : BASE_CHECKIN * 2;
    CHECKIN_AT_PLACE_WITH_MORE_THAN_1000_CHECKINS : BASE_CHECKIN * 4;
    CHECKIN_AT_PLACE_WITH_MORE_THAN_10000_CHECKINS : BASE_CHECKIN * 6;
    CHECKIN_AT_PLACE_REMOTE_FROM_LAST_AT_1000KM : BASE_CHECKIN * 5;
    CHECKIN_AT_PLACE_REMOTE_FROM_LAST_AT_5000KM : BASE_CHECKIN * 10;
    CHECKIN_AT_PLACE_REMOTE_FROM_LAST_AT_10000KM : BASE_CHECKIN * 100;

    CHECKIN_AT_JUST_CREATED_PLACE : BASE_CHECKIN * 10; // curiosity
    CHECKIN_AT_NEW_CATEGORY : BASE_CHECKIN * 5; // curiosity
    CHECKIN_WITH_ONE_FRIEND : BASE_CHECKIN * 5; // sociality
    CHECKIN_WITH_TOP_SPEED_MORE_THAN_100KMH : BASE_CHECKIN * 5; // curiosity
    CHECKIN_WITH_TOP_SPEED_MORE_THAN_500KMH : BASE_CHECKIN * 10; // curiosity

    EACH_FRIEND : 100; // sociality
    EACH_YOUR_FOLLOWER_WITHOUT_MUTUALITY : 10; //charisma
  }
}
