/* @flow */

var FoursquareConst = function() {
  this.ONE_KILOMETER_PASSED = 1;
  var BASE_CHECKIN = this.BASE_CHECKIN = 10;
  this.ONE_LIKE_TO_CHECKIN = BASE_CHECKIN * 2;
  this.CHECKIN_WITH_PHOTO = BASE_CHECKIN * 2;
  this.ONE_COMMENT_TO_CHECKIN = BASE_CHECKIN * 3;
  this.NEW_PLACE_CHECKIN = BASE_CHECKIN * 5;
  this.MAYORSHIP_CHECKIN = BASE_CHECKIN * 5;
  this.CHECKIN_WITH_NEW_FOURSQUARE_CLIENT = BASE_CHECKIN * 5;
  this.CHECKIN_AT_PLACE_WITH_MORE_THAN_100_CHECKINS = BASE_CHECKIN * 2;
  this.CHECKIN_AT_PLACE_WITH_MORE_THAN_1000_CHECKINS = BASE_CHECKIN * 4;
  this.CHECKIN_AT_PLACE_WITH_MORE_THAN_10000_CHECKINS = BASE_CHECKIN * 6;
  this.CHECKIN_AT_PLACE_REMOTE_FROM_LAST_AT_1000KM = BASE_CHECKIN * 5;
  this.CHECKIN_AT_PLACE_REMOTE_FROM_LAST_AT_5000KM = BASE_CHECKIN * 10;
  this.CHECKIN_AT_PLACE_REMOTE_FROM_LAST_AT_10000KM = BASE_CHECKIN * 100;

  this.CHECKIN_AT_JUST_CREATED_PLACE = BASE_CHECKIN * 10; // curiosity
  this.CHECKIN_AT_NEW_CATEGORY = BASE_CHECKIN * 5; // curiosity
  this.CHECKIN_WITH_ONE_FRIEND = BASE_CHECKIN * 5; // sociality
  this.CHECKIN_WITH_TOP_SPEED_MORE_THAN_100KMH = BASE_CHECKIN * 5; // curiosity
  this.CHECKIN_WITH_TOP_SPEED_MORE_THAN_500KMH = BASE_CHECKIN * 10; // curiosity

  this.EACH_FRIEND = 100; // sociality
  this.EACH_YOUR_FOLLOWER_WITHOUT_MUTUALITY = 10; //charisma
}
module.exports = {
  LEVELFX_LOGARITHM_BASE : 10,
  Foursquare: FoursquareConst
}
